name: healthcare_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  sqflite: ^2.3.0
  path: ^1.8.3
  lottie: ^2.6.0
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
